name = "General Arma Utilities"
author = "DartRuffian"
prefix = "gau"
mainprefix = "z"

[version]
path = "addons/main/script_version.hpp"
git_hash = 0

[files]
include = [
    "mod.cpp",
    "meta.cpp",
    "logo_gau.png",
    "logo_gau_ca.paa",
    "LICENSE.md",
    "README.md",
]
exclude = []

[hemtt.release]
archive = false

[properties]
author = "DartRuffian"