name = "Sci-Fi Tweaks"
author = "DartRuffian"
prefix = "sft"
mainprefix = "z"

[version]
path = "addons/main/script_version.hpp"
git_hash = 0

[files]
include = [
    "mod.cpp",
    "meta.cpp",
    "logo_sft.png",
    "logo_sft_ca.paa",
    "LICENSE.md",
    "README.md",
]
exclude = []

[hemtt.release]
archive = false

[properties]
author = "DartRuffian"