name = "Sci-Fi Systems"
author = "DartRuffian"
prefix = "sfs"
mainprefix = "z"

[version]
path = "addons/main/script_version.hpp"
git_hash = 0

[files]
include = [
    "mod.cpp",
    "meta.cpp",
    "logo_sfs.png",
    "logo_sfs_ca.paa",
    "LICENSE.md",
    "README.md",
]
exclude = []

[hemtt.release]
archive = false

[properties]
author = "DartRuffian"